### ISSUE TITLE
judge-simple_form gem not working with Rails 5.0.0.rc1

### ISSUE THREAD

**Issue by KudosX** [joecorcoran/judge-simple_form#19]
able to get Judge gem to work without simple_form here: https://github.com/KudosX/devise_inline_validation_judge
But, when I include simple_form gem and judge-simple_form it doesn't work. 
Repo here:
https://github.com/KudosX/judge_simple
I get this error:
undefined method 'error_notification' for #<Judge::FormBuilder:xxxxxx> in views/devise/registrations/new.html.erb
